// <auto-generated />
namespace ConsoleEntity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ClienteCpf : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClienteCpf));
        
        string IMigrationMetadata.Id
        {
            get { return "202207052313382_ClienteCpf"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
